### ISSUE TITLE
这样部署真感觉不方便管理图片

### ISSUE THREAD

**Issue by Megasu** [fouber/static-resource-digest-project#6]
所有图片为什么不发布到同一级目录下管理。

现在的是Css和图片都是同一级目录的。

**Comment by fouber** [comment]
@Megasu 

目录结构自己随便修改，没有限制的

**Comment by Megasu** [comment]
是可以自己随便改，只是想了解一下这个规范设计的初衷。

**Comment by Megasu** [comment]
是可以自己随便改，只是想了解一下这个规范设计的初衷。

**Comment by fouber** [comment]
@Megasu 

只是为了方便理解，并非规范
